# ワークフローの名前
name: Java CI with Maven

# ワークフローをトリガーするイベント
on:
  push:
    branches: [ main ]

# 実行するジョブ
jobs:
  build:
    # 実行するランナーのオペレーティングシステム
    runs-on: ubuntu-latest

    # 実行するステップ
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v2
      
      # Javaのセットアップ
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' # JDK11からJDK21に変更
          distribution: 'temurin' # Eclipse Temurinを使用
      
      # Mavenを使ってビルドとテストの実行
      - name: Build with Maven
        run: mvn -B package --file pom.xml
